# To run current docker compose file, you should prepare the silliconflow api key in your environment.
# SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY} docker compose up -d
services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'aa123456'
    ports:
      - 3306:3306
    volumes:
      - dbgpt-myql-db:/var/lib/mysql
      - ./docker/examples/my.cnf:/etc/my.cnf
      - ./docker/examples/sqls:/docker-entrypoint-initdb.d
      - ./assets/schema/dbgpt.sql:/docker-entrypoint-initdb.d/dbgpt.sql
    restart: unless-stopped
    networks:
      - dbgptnet
  # ---------- TuGraph ----------
  tugraph:
    image: tugraph/tugraph-runtime-centos7:4.5.1   # ← 用你真实拉到的镜像
    platform: linux/amd64          # Apple Silicon 必填
    container_name: tugraph
    ports:
      - "7687:7687"        # Bolt Port
      - "7070:7070"        # TuGraph Web Port (可选)
    environment:
      - LGRAPH_LISTEN_HOST=0.0.0.0
      - LGRAPH_LISTEN_PORT=7687
    volumes:
      - ./tugraph-data:/data
    networks: [dbgptnet]
  webserver:
    image: eosphorosai/dbgpt-openai:latest
    command: dbgpt start webserver --config /app/configs/dbgpt-proxy-siliconflow-mysql.toml
    environment:
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - CONFIG_PATH=configs/dbgpt-graphrag.toml
      - MYSQL_PASSWORD=aa123456
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dbgpt
      - MYSQL_USER=root
    volumes:
      - ./configs:/app/configs
      - ./data:/data
      # May be you can mount your models to container
      - ./data/models:/app/models
      - dbgpt-data:/app/pilot/data
      - dbgpt-message:/app/pilot/message
    depends_on:
      - db
      - tugraph
    ports:
      - 5670:5670/tcp
    # webserver may be failed, it must wait all sqls in /docker-entrypoint-initdb.d execute finish.
    restart: unless-stopped
    networks:
      - dbgptnet
    ipc: host
volumes:
  dbgpt-myql-db:
  dbgpt-data:
  dbgpt-message:
  dbgpt-alembic-versions:
networks:
  dbgptnet:
    driver: bridge
    name: dbgptnet
